#!/usr/bin/env bash
# shellcheck disable=SC2034  # 常量、选项与向导变量跨分区或经 bash 动态作用域使用，逐个标注噪音过大
# llamapad 部署管理脚本：安装、初始化、启停、配置、升级、自检、卸载（单文件，bash 3.2+）
#
# 安装：curl -fsSL https://raw.githubusercontent.com/LanceLRQ/llamapad/main/deploy/llamapad.sh | bash
# 管理：llamapad [命令] [--dir 目录] [--lang zh|en]
#
# LLAMAPAD_SOURCE_ONLY=1 时只定义函数、不执行 main（供测试 source）。

# 以 sh 调用时改用 bash 重新执行。这几行必须保持 POSIX sh 兼容
if [ -z "${BASH_VERSION:-}" ]; then
  if [ -f "$0" ] && command -v bash >/dev/null 2>&1; then exec bash "$0" "$@"; fi
  echo "llamapad.sh requires bash / 需要用 bash 运行" >&2
  exit 1
fi

# ===== 1. 常量与可覆盖路径 =====

LLAMAPAD_SCRIPT_VERSION="0.1.0"
LLAMAPAD_TEMPLATE_VERSION=1
LLAMAPAD_IMAGE="lancelrq/llamapad"
LLAMAPAD_CONTAINER="llamapad"
LLAMAPAD_DEFAULT_HOME="/opt/llamapad"
LLAMAPAD_DEFAULT_PORT=28960
LLAMAPAD_MIN_FREE_KB=$((100 * 1024 * 1024))

# 以下路径与命令均可被环境变量覆盖：测试注入桩，或特殊环境（镜像加速、非常规安装位置）
LP_BIN_DIR="${LLAMAPAD_BIN_DIR:-/usr/local/bin}"
LP_DOCKER="${LLAMAPAD_DOCKER_BIN:-docker}"
LP_SUDO="${LLAMAPAD_SUDO:-sudo}"
LP_NVIDIA_SMI="${LLAMAPAD_NVIDIA_SMI:-nvidia-smi}"
LP_DOCKER_SOCK="${LLAMAPAD_DOCKER_SOCK:-/var/run/docker.sock}"
LP_SYSFS="${LLAMAPAD_SYSFS:-/sys}"
LP_PROC="${LLAMAPAD_PROC:-/proc}"
LP_ETC="${LLAMAPAD_ETC:-/etc}"
LP_TTY="${LLAMAPAD_TTY:-/dev/tty}"
LP_RAW_BASE="${LLAMAPAD_RAW_BASE:-https://raw.githubusercontent.com/LanceLRQ/llamapad}"
LP_HUB_TAGS_URL="${LLAMAPAD_HUB_TAGS_URL:-https://hub.docker.com/v2/repositories/lancelrq/llamapad/tags?page_size=100}"

# 脚本自身路径：curl | bash 时为空（读不到自身文件，安装时改为按版本重新下载）
LP_SELF="${BASH_SOURCE[0]:-}"

LP_LANG=en
LP_HOME=""
OPT_DIR=""
OPT_LANG=""
OPT_TO=""
OPT_FOLLOW=0
CMD=""

# ===== 2. i18n =====
# 文案表：MSG_<zh|en>_<key>，值是 printf 格式串。两种语言的键集合必须一致（测试守护）

MSG_zh_usage='用法：llamapad [命令] [选项]'
MSG_en_usage='Usage: llamapad [command] [options]'
MSG_zh_help_commands_title='命令：'
MSG_en_help_commands_title='Commands:'
MSG_zh_help_options_title='选项：'
MSG_en_help_options_title='Options:'
MSG_zh_help_install='安装并初始化（未安装时直接运行脚本即进入）'
MSG_en_help_install='Install and initialize (default when not installed yet)'
MSG_zh_help_start='启动面板'
MSG_en_help_start='Start the panel'
MSG_zh_help_stop='停止面板'
MSG_en_help_stop='Stop the panel'
MSG_zh_help_restart='重建并重启面板（配置变更后用它生效）'
MSG_en_help_restart='Recreate and restart the panel (applies config changes)'
MSG_zh_help_status='查看运行状态'
MSG_en_help_status='Show status'
MSG_zh_help_logs='查看面板日志（-f 持续跟随）'
MSG_en_help_logs='Show panel logs (-f to follow)'
MSG_zh_help_config='修改配置'
MSG_en_help_config='Change configuration'
MSG_zh_help_upgrade='升级脚本与镜像（--to 指定版本）'
MSG_en_help_upgrade='Upgrade the script and image (--to for a specific version)'
MSG_zh_help_doctor='环境自检'
MSG_en_help_doctor='Check the environment'
MSG_zh_help_uninstall='卸载'
MSG_en_help_uninstall='Uninstall'
MSG_zh_help_help='显示本帮助'
MSG_en_help_help='Show this help'
MSG_zh_help_version='显示脚本版本'
MSG_en_help_version='Show the script version'
MSG_zh_help_opt_dir='指定部署目录'
MSG_en_help_opt_dir='Deployment directory'
MSG_zh_help_opt_lang='界面语言'
MSG_en_help_opt_lang='Interface language'
MSG_zh_help_opt_to='upgrade 的目标版本'
MSG_en_help_opt_to='Target version for upgrade'
MSG_zh_help_opt_follow='logs 持续跟随输出'
MSG_en_help_opt_follow='Follow output for logs'
MSG_zh_unknown_option='未知选项：%s'
MSG_en_unknown_option='Unknown option: %s'
MSG_zh_extra_argument='多余的参数：%s'
MSG_en_extra_argument='Unexpected argument: %s'
MSG_zh_need_root='该操作需要 root 权限，但当前不是 root 且没有可用的 sudo'
MSG_en_need_root='This step needs root, but you are not root and sudo is not available'
MSG_zh_docker_sudo_note='当前用户无权访问 docker.sock（不是 root 也不在 docker 组），接下来的 docker 命令将通过 sudo 执行，可能需要输入密码'
MSG_en_docker_sudo_note='Your user cannot access docker.sock (not root and not in the docker group); docker commands will run through sudo and may ask for your password'
MSG_zh_docker_missing='未找到 docker 命令。请先安装 Docker Engine：https://docs.docker.com/engine/install/'
MSG_en_docker_missing='The docker command was not found. Install Docker Engine first: https://docs.docker.com/engine/install/'
MSG_zh_docker_daemon_down='无法连接 Docker daemon。请确认服务已启动（systemctl start docker）'
MSG_en_docker_daemon_down='Cannot connect to the Docker daemon. Make sure it is running (systemctl start docker)'
MSG_zh_docker_rootless='检测到 rootless Docker，本脚本暂不支持（面板需要挂载 /var/run/docker.sock）'
MSG_en_docker_rootless='Rootless Docker detected, which this script does not support yet (the panel mounts /var/run/docker.sock)'
MSG_zh_docker_no_compose='缺少 docker compose v2 插件：https://docs.docker.com/compose/install/linux/'
MSG_en_docker_no_compose='The docker compose v2 plugin is missing: https://docs.docker.com/compose/install/linux/'
MSG_zh_docker_unknown='Docker 状态未知'
MSG_en_docker_unknown='Docker status unknown'
MSG_zh_env_header_1='# llamapad 部署配置（由 llamapad.sh 生成）。可以手改：脚本只按键替换，不会删除你的注释与自定义变量'
MSG_en_env_header_1='# llamapad deployment config (generated by llamapad.sh). Safe to edit by hand: the script only replaces keys and keeps your comments and extra variables'
MSG_zh_env_header_2='# 含管理员密码，请勿提交到版本库或外传'
MSG_en_env_header_2='# Contains the admin password; do not commit or share it'
MSG_zh_chown_need_root='需要 root 权限把 %s 的属主改为 %s'
MSG_en_chown_need_root='Root is needed to change the owner of %s to %s'
MSG_zh_mkdir_need_root='需要 root 权限创建目录 %s'
MSG_en_mkdir_need_root='Root is needed to create %s'
MSG_zh_ui_menu_hint='↑↓ 选择   Enter 确认   q 返回'
MSG_en_ui_menu_hint='↑↓ select   Enter confirm   q back'
MSG_zh_ui_number_prompt='请输入序号（q 返回）：'
MSG_en_ui_number_prompt='Enter a number (q to go back): '
MSG_zh_ui_yes='是'
MSG_en_ui_yes='Yes'
MSG_zh_ui_no='否'
MSG_en_ui_no='No'
MSG_zh_ui_press_enter='按 Enter 继续…'
MSG_en_ui_press_enter='Press Enter to continue…'
MSG_zh_unsupported_platform='本脚本只支持 Linux 宿主机'
MSG_en_unsupported_platform='This script only supports Linux hosts'
MSG_zh_no_tty='无法打开终端进行交互。请改为先下载再执行：curl -fsSLO <地址> && bash llamapad.sh'
MSG_en_no_tty='Cannot open a terminal for interaction. Download first, then run: curl -fsSLO <url> && bash llamapad.sh'
MSG_zh_install_welcome='llamapad 部署管理脚本 v%s —— 开始安装'
MSG_en_install_welcome='llamapad deployment script v%s — starting installation'
MSG_zh_ask_install_dir='安装目录'
MSG_en_ask_install_dir='Install directory'
MSG_zh_install_dir_invalid='目录路径不能包含空格或冒号'
MSG_en_install_dir_invalid='The directory path cannot contain spaces or colons'
MSG_zh_already_installed='%s 已经安装过，进入管理菜单'
MSG_en_already_installed='%s is already installed; opening the management menu'
MSG_zh_dir_need_root='没有权限写入 %s，是否用 sudo 创建并把属主改为当前用户？'
MSG_en_dir_need_root='No permission to write %s. Create it with sudo and hand it to the current user?'
MSG_zh_launcher_overwrite='%s 已存在且指向其他安装，是否覆盖？'
MSG_en_launcher_overwrite='%s already exists and points to another installation. Overwrite it?'
MSG_zh_launcher_need_sudo='写入 %s 需要 root 权限，是否使用 sudo？'
MSG_en_launcher_need_sudo='Writing %s needs root. Use sudo?'
MSG_zh_launcher_skipped='已跳过 llamapad 命令，之后请用 %s 管理'
MSG_en_launcher_skipped='Skipped the llamapad command; use %s to manage the panel'
MSG_zh_launcher_done='已安装命令：%s（任意目录执行 llamapad 即可管理）'
MSG_en_launcher_done='Installed command: %s (run llamapad from any directory)'
MSG_zh_self_download_failed='下载脚本失败（可设置 LLAMAPAD_RAW_BASE 指向可访问的镜像地址）'
MSG_en_self_download_failed='Failed to download the script (set LLAMAPAD_RAW_BASE to a reachable mirror)'
MSG_zh_self_syntax_failed='下载的脚本未通过语法检查，已放弃'
MSG_en_self_syntax_failed='The downloaded script failed the syntax check and was discarded'
MSG_zh_unknown_command='未知命令：%s'
MSG_en_unknown_command='Unknown command: %s'
MSG_zh_not_installed='llamapad 尚未安装（或未找到部署目录），请先运行 llamapad.sh 安装，或用 --dir 指定部署目录'
MSG_en_not_installed='llamapad is not installed (or the deployment directory was not found). Run llamapad.sh to install, or pass --dir'
MSG_zh_wizard_intro='接下来逐项配置，最后会有汇总页可以回头修改；确认之前不会写入任何配置文件'
MSG_en_wizard_intro='Configure each item below; a summary page at the end lets you revise anything. Nothing is written until you confirm'
MSG_zh_ask_models_dir='选择模型库位置（GGUF 文件动辄数十 GB，建议放在大容量数据盘）'
MSG_en_ask_models_dir='Choose the model library location (GGUF files are often tens of GB; prefer a large data disk)'
MSG_zh_disk_manual='手动输入路径…'
MSG_en_disk_manual='Enter a path…'
MSG_zh_disk_free='剩余 %s'
MSG_en_disk_free='%s free'
MSG_zh_disk_system='系统盘'
MSG_en_disk_system='system disk'
MSG_zh_disk_low_space='⚠ 空间偏小'
MSG_en_disk_low_space='⚠ low space'
MSG_zh_disk_network_slow='网络盘，读取模型会慢'
MSG_en_disk_network_slow='network storage, model loading will be slow'
MSG_zh_disk_type_nvme='NVMe'
MSG_en_disk_type_nvme='NVMe'
MSG_zh_disk_type_ssd='SSD'
MSG_en_disk_type_ssd='SSD'
MSG_zh_disk_type_hdd='HDD'
MSG_en_disk_type_hdd='HDD'
MSG_zh_disk_type_mixed='混合'
MSG_en_disk_type_mixed='Mixed'
MSG_zh_disk_type_network='网络'
MSG_en_disk_type_network='Network'
MSG_zh_disk_type_unknown='未知'
MSG_en_disk_type_unknown='Unknown'
MSG_zh_ask_models_path='模型库绝对路径'
MSG_en_ask_models_path='Absolute path of the model library'
MSG_zh_models_path_invalid='请输入绝对路径，且不能包含空格、冒号或引号'
MSG_en_models_path_invalid='Enter an absolute path without spaces, colons or quotes'
MSG_zh_models_found='该目录已有 %s 个 GGUF 文件，共 %s'
MSG_en_models_found='Found %s GGUF files (%s) in this directory'
MSG_zh_ask_identity='面板运行身份（必须对 data/ 与模型库可写）'
MSG_en_ask_identity='Panel runtime identity (must be able to write data/ and the model library)'
MSG_zh_identity_follow='跟随模型库属主 %s（推荐）'
MSG_en_identity_follow='Match the model library owner %s (recommended)'
MSG_zh_identity_new='普通用户 1000:1000（推荐，新建目录会自动对齐属主）'
MSG_en_identity_new='Regular user 1000:1000 (recommended; new directories are chowned automatically)'
MSG_zh_identity_current='当前用户 %s'
MSG_en_identity_current='Current user %s'
MSG_zh_identity_root='root 0:0'
MSG_en_identity_root='root 0:0'
MSG_zh_identity_custom='自定义…'
MSG_en_identity_custom='Custom…'
MSG_zh_ask_uid_gid='UID:GID'
MSG_en_ask_uid_gid='UID:GID'
MSG_zh_uid_gid_invalid='格式应为 数字:数字，例如 1000:1000'
MSG_en_uid_gid_invalid='Use the form number:number, e.g. 1000:1000'
MSG_zh_gpu_none='未检测到 NVIDIA GPU，面板将以无 GPU 方式运行'
MSG_en_gpu_none='No NVIDIA GPU detected; the panel will run without GPU'
MSG_zh_gpu_found='检测到 GPU：'
MSG_en_gpu_found='GPUs detected:'
MSG_zh_ask_gpu_enable='启用 GPU？'
MSG_en_ask_gpu_enable='Enable GPU?'
MSG_zh_gpu_no_toolkit='检测到显卡，但 Docker 没有 NVIDIA 运行时。请先安装 nvidia-container-toolkit：https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html'
MSG_en_gpu_no_toolkit='GPUs found, but Docker has no NVIDIA runtime. Install nvidia-container-toolkit first: https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html'
MSG_zh_ask_gpu_enable_anyway='仍然启用 GPU？（缺运行时容器会起不来）'
MSG_en_ask_gpu_enable_anyway='Enable GPU anyway? (the container will not start without the runtime)'
MSG_zh_ask_port='面板端口'
MSG_en_ask_port='Panel port'
MSG_zh_port_invalid='端口须是 1-65535 之间的数字'
MSG_en_port_invalid='The port must be a number between 1 and 65535'
MSG_zh_port_busy='端口 %s 已被占用'
MSG_en_port_busy='Port %s is already in use'
MSG_zh_ask_bind='监听地址'
MSG_en_ask_bind='Listen address'
MSG_zh_bind_all='0.0.0.0（所有网卡）'
MSG_en_bind_all='0.0.0.0 (all interfaces)'
MSG_zh_bind_local='127.0.0.1（仅本机，放在 HTTPS 反代之后时推荐）'
MSG_en_bind_local='127.0.0.1 (local only; recommended behind an HTTPS reverse proxy)'
MSG_zh_bind_custom='自定义…'
MSG_en_bind_custom='Custom…'
MSG_zh_ask_bind_ip='IPv4 地址'
MSG_en_ask_bind_ip='IPv4 address'
MSG_zh_bind_invalid='请输入合法的 IPv4 地址'
MSG_en_bind_invalid='Enter a valid IPv4 address'
MSG_zh_ask_password='管理员密码（留空则随机生成）'
MSG_en_ask_password='Admin password (leave empty to generate one)'
MSG_zh_ask_password_again='再输入一次'
MSG_en_ask_password_again='Repeat the password'
MSG_zh_password_too_short='密码至少 8 位'
MSG_en_password_too_short='The password must be at least 8 characters'
MSG_zh_password_bad_char='密码不能包含单引号'
MSG_en_password_bad_char='The password cannot contain single quotes'
MSG_zh_password_mismatch='两次输入不一致'
MSG_en_password_mismatch='The passwords do not match'
MSG_zh_ask_timezone='时区'
MSG_en_ask_timezone='Timezone'
MSG_zh_timezone_invalid='时区不能为空或包含空格'
MSG_en_timezone_invalid='The timezone cannot be empty or contain spaces'
MSG_zh_ask_llm='配置外部 LLM？（用于解析模型 README 里的推荐参数，可稍后在面板设置页配置）'
MSG_en_ask_llm='Configure an external LLM? (parses recommended parameters from model READMEs; can be set later in panel settings)'
MSG_zh_ask_llm_base_url='Base URL（填到 /v1 为止）'
MSG_en_ask_llm_base_url='Base URL (up to /v1)'
MSG_zh_ask_llm_api_key='API Key'
MSG_en_ask_llm_api_key='API Key'
MSG_zh_ask_llm_model='模型名'
MSG_en_ask_llm_model='Model name'
MSG_zh_summary_title='确认配置（选中某项可修改）'
MSG_en_summary_title='Review the configuration (select an item to change it)'
MSG_zh_summary_confirm='✔ 确认并写入'
MSG_en_summary_confirm='✔ Confirm and write'
MSG_zh_summary_cancel='✘ 取消安装'
MSG_en_summary_cancel='✘ Cancel installation'
MSG_zh_summary_models='模型库：%s'
MSG_en_summary_models='Model library: %s'
MSG_zh_summary_identity='运行身份：%s'
MSG_en_summary_identity='Runtime identity: %s'
MSG_zh_summary_gpu='GPU：%s'
MSG_en_summary_gpu='GPU: %s'
MSG_zh_summary_port='端口：%s'
MSG_en_summary_port='Port: %s'
MSG_zh_summary_bind='监听地址：%s'
MSG_en_summary_bind='Listen address: %s'
MSG_zh_summary_password='管理员密码：%s'
MSG_en_summary_password='Admin password: %s'
MSG_zh_summary_timezone='时区：%s'
MSG_en_summary_timezone='Timezone: %s'
MSG_zh_summary_llm='外部 LLM：%s'
MSG_en_summary_llm='External LLM: %s'
MSG_zh_value_enabled='启用'
MSG_en_value_enabled='enabled'
MSG_zh_value_disabled='不启用'
MSG_en_value_disabled='disabled'
MSG_zh_value_not_configured='未配置'
MSG_en_value_not_configured='not configured'
MSG_zh_value_generated='随机生成'
MSG_en_value_generated='generated'
MSG_zh_install_cancelled='已取消，未写入任何配置'
MSG_en_install_cancelled='Cancelled; no configuration was written'
MSG_zh_apply_failed='写入部署文件失败'
MSG_en_apply_failed='Failed to write the deployment files'
MSG_zh_install_written='部署文件已写入 %s'
MSG_en_install_written='Deployment files written to %s'
MSG_zh_ask_start_now='现在拉取镜像并启动面板？'
MSG_en_ask_start_now='Pull the image and start the panel now?'
MSG_zh_install_done='安装完成'
MSG_en_install_done='Installation complete'
MSG_zh_final_urls='访问地址：'
MSG_en_final_urls='Open the panel at:'
MSG_zh_final_password_generated='管理员密码（随机生成，只显示这一次，已写入 .env）：%s'
MSG_en_final_password_generated='Admin password (generated, shown only once, saved in .env): %s'
MSG_zh_final_env_location='配置文件：%s（改密码、端口等可用 llamapad config）'
MSG_en_final_env_location='Config file: %s (use llamapad config to change the password, port, etc.)'
MSG_zh_final_commands='常用命令：llamapad（菜单）· llamapad start · llamapad status · llamapad logs -f'
MSG_en_final_commands='Common commands: llamapad (menu) · llamapad start · llamapad status · llamapad logs -f'
MSG_zh_env_missing='部署目录里没有 .env，请重新运行安装或 llamapad config'
MSG_en_env_missing='No .env in the deployment directory; rerun the installer or llamapad config'
MSG_zh_gid_synced='docker.sock 的 gid 变为 %s，已更新 .env'
MSG_en_gid_synced='docker.sock gid is now %s; .env updated'
MSG_zh_models_missing='模型库目录不存在：%s（用 llamapad config 修改位置）'
MSG_en_models_missing='The model library directory does not exist: %s (change it with llamapad config)'
MSG_zh_data_owner_mismatch='data/ 的属主（%s）与运行身份（%s）不一致，面板将无法写入数据库'
MSG_en_data_owner_mismatch='data/ is owned by %s but the panel runs as %s; it will not be able to write its database'
MSG_zh_ask_fix_owner='现在修正 data/ 的属主？'
MSG_en_ask_fix_owner='Fix the owner of data/ now?'
MSG_zh_gpu_runtime_missing='已启用 GPU，但 Docker 没有 NVIDIA 运行时（需要 nvidia-container-toolkit），或用 llamapad config 关闭 GPU'
MSG_en_gpu_runtime_missing='GPU is enabled but Docker has no NVIDIA runtime (install nvidia-container-toolkit), or disable GPU with llamapad config'
MSG_zh_starting='正在启动面板…'
MSG_en_starting='Starting the panel…'
MSG_zh_restarting='正在重建并重启面板…'
MSG_en_restarting='Recreating and restarting the panel…'
MSG_zh_start_failed='docker compose 执行失败'
MSG_en_start_failed='docker compose failed'
MSG_zh_panel_ready='面板已就绪'
MSG_en_panel_ready='The panel is ready'
MSG_zh_panel_not_ready='面板在 %s 秒内未就绪，请用 llamapad logs 查看日志'
MSG_en_panel_not_ready='The panel was not ready within %s seconds; check llamapad logs'
MSG_zh_access_title='访问地址：'
MSG_en_access_title='Open the panel at:'
MSG_zh_stopped='面板已停止'
MSG_en_stopped='The panel has stopped'
MSG_zh_stop_failed='停止失败'
MSG_en_stop_failed='Failed to stop the panel'
MSG_zh_models_still_running='以下模型容器仍在运行（停止面板不会停止它们）：%s'
MSG_en_models_still_running='These model containers are still running (stopping the panel does not stop them): %s'
MSG_zh_ask_stop_models='一并停止这些模型容器？'
MSG_en_ask_stop_models='Stop these model containers too?'
MSG_zh_status_panel='面板：%s'
MSG_en_status_panel='Panel: %s'
MSG_zh_status_not_created='未创建'
MSG_en_status_not_created='not created'
MSG_zh_status_image='镜像：%s:%s'
MSG_en_status_image='Image: %s:%s'
MSG_zh_status_listen='监听：%s:%s'
MSG_en_status_listen='Listening on: %s:%s'
MSG_zh_status_model='运行中的模型：%s'
MSG_en_status_model='Running model: %s'
MSG_zh_status_model_none='无'
MSG_en_status_model_none='none'
MSG_zh_status_gpu='GPU：%s'
MSG_en_status_gpu='GPU: %s'
MSG_zh_status_disk='%s 所在磁盘剩余 %s'
MSG_en_status_disk='Disk holding %s: %s free'
MSG_zh_menu_title='llamapad 部署管理'
MSG_en_menu_title='llamapad deployment manager'
MSG_zh_menu_versions='脚本 v%s · 镜像 %s'
MSG_en_menu_versions='script v%s · image %s'
MSG_zh_menu_dir='目录 %s'
MSG_en_menu_dir='Directory %s'
MSG_zh_item_start='启动'
MSG_en_item_start='Start'
MSG_zh_item_restart='重启'
MSG_en_item_restart='Restart'
MSG_zh_item_stop='停止'
MSG_en_item_stop='Stop'
MSG_zh_item_status='查看状态'
MSG_en_item_status='Status'
MSG_zh_item_logs='查看日志（最近 200 行；持续跟随请用 llamapad logs -f）'
MSG_en_item_logs='Logs (last 200 lines; use llamapad logs -f to follow)'
MSG_zh_item_config='修改配置'
MSG_en_item_config='Change configuration'
MSG_zh_item_upgrade='升级'
MSG_en_item_upgrade='Upgrade'
MSG_zh_item_doctor='环境自检'
MSG_en_item_doctor='Check environment'
MSG_zh_item_uninstall='卸载'
MSG_en_item_uninstall='Uninstall'
MSG_zh_item_exit='退出'
MSG_en_item_exit='Exit'
MSG_zh_config_title='修改配置（改完返回时可选择立即生效）'
MSG_en_config_title='Change configuration (you can apply the changes when leaving)'
MSG_zh_config_password='管理员密码…'
MSG_en_config_password='Admin password…'
MSG_zh_config_back='返回'
MSG_en_config_back='Back'
MSG_zh_config_models_note='模型文件不会被搬动：已有模型配置里的路径相对模型库根目录，换位置后需自行把文件移过去'
MSG_en_config_models_note='Model files are not moved: model configs use paths relative to the library root, so move the files yourself after relocating'
MSG_zh_config_password_generated='新的管理员密码：%s'
MSG_en_config_password_generated='New admin password: %s'
MSG_zh_config_password_note='重启面板后新密码生效，所有已登录的浏览器需要重新登录（API Token 不受影响）'
MSG_en_config_password_note='The new password applies after the panel restarts; every logged-in browser will have to sign in again (API Tokens are unaffected)'
MSG_zh_ask_apply_now='配置已修改，现在重建面板容器使其生效？'
MSG_en_ask_apply_now='Configuration changed. Recreate the panel container now to apply it?'
MSG_zh_config_apply_later='稍后用 llamapad restart 使修改生效'
MSG_en_config_apply_later='Run llamapad restart later to apply the changes'
MSG_zh_identity_apply_failed='数据目录属主修改失败，运行身份未更改'
MSG_en_identity_apply_failed='Failed to change the data directory owner; the run identity was not changed'
MSG_zh_value_bad_char='不能包含单引号或换行'
MSG_en_value_bad_char='Must not contain single quotes or newlines'

# t <key> [参数...]：按当前语言输出文案；键未定义时输出键名本身，便于发现遗漏
t() {
  local name="MSG_${LP_LANG}_$1" fmt
  fmt="${!name}"
  [ -n "$fmt" ] || fmt="$1"
  shift
  # shellcheck disable=SC2059
  printf -- "$fmt" "$@"
}

# 语言判定：--lang > LLAMAPAD_LANG > LC_ALL > LANG；zh 开头为中文，其余英文
detect_lang() {
  local v="${OPT_LANG:-${LLAMAPAD_LANG:-${LC_ALL:-${LANG:-}}}}"
  case "$v" in
    zh*) LP_LANG=zh ;;
    *) LP_LANG=en ;;
  esac
}

# ===== 3. 输出与通用工具 =====

# 颜色只在 stderr 是终端且未设 NO_COLOR 时启用
lp_color_on() { [ -z "${NO_COLOR:-}" ] && [ -t 2 ]; }
lp_sgr() { if lp_color_on; then printf '\033[%sm' "$1"; fi; }

# 提示信息一律写 stderr：stdout 留给可被 $(...) 捕获的函数返回值
info() { printf '%s\n' "$*" >&2; }
ok() { printf '%s✔%s %s\n' "$(lp_sgr 32)" "$(lp_sgr 0)" "$*" >&2; }
warn() { printf '%s⚠%s %s\n' "$(lp_sgr 33)" "$(lp_sgr 0)" "$*" >&2; }
err() { printf '%s✘%s %s\n' "$(lp_sgr 31)" "$(lp_sgr 0)" "$*" >&2; }

# 单引号转义，结果可安全拼进 sh 命令行
sh_quote() {
  printf "'%s'" "$(printf '%s' "$1" | sed "s/'/'\\\\''/g")"
}

# 转绝对路径：展开 ~、拼 PWD、去掉 /./ 与末尾斜杠（不解析 .. 与符号链接）
abs_path() {
  local p="$1"
  # shellcheck disable=SC2088  # 下面是 case 模式匹配字面量 "~/"，不是期待展开的命令参数，误报；
  # 指令只能放在完整命令（这里是 case）前，放在单个分支前 ShellCheck 会报语法错误
  case "$p" in
    "~") p="$HOME" ;;
    "~/"*) p="$HOME/${p#\~/}" ;;
  esac
  case "$p" in
    /*) ;;
    *) p="$PWD/$p" ;;
  esac
  while :; do
    case "$p" in
      */./*) p="${p%%/./*}/${p#*/./}" ;;
      *) break ;;
    esac
  done
  case "$p" in */.) p="${p%/.}" ;; esac
  [ "$p" = / ] || p="${p%/}"
  printf '%s' "${p:-/}"
}

# 属主 uid:gid（GNU/busybox 用 -c，BSD 用 -f）
stat_owner() {
  stat -c '%u:%g' "$1" 2>/dev/null || stat -f '%u:%g' "$1" 2>/dev/null
}

sha256_file() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | awk '{print $1}'
  else
    shasum -a 256 "$1" | awk '{print $1}'
  fi
}

# 随机字母数字串（默认 20 位）
gen_password() {
  LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom 2>/dev/null | head -c "${1:-20}"
}

# KB → 38G / 1.2T 这种写法：≥10 取整，<10 保留一位小数
fmt_kb() {
  awk -v k="$1" 'BEGIN {
    split("K M G T P", u, " "); v = k + 0; i = 1
    while (v >= 1024 && i < 5) { v /= 1024; i++ }
    if (v >= 10 || i == 1) printf "%d%s", v, u[i]; else printf "%.1f%s", v, u[i]
  }'
}

# ===== 4. .env / state / 版本 =====

# .env 值的写法：只含安全字符时原样写，否则单引号包裹（compose 对单引号值不做 $ 插值）
env_quote() {
  case "$1" in
    *[!A-Za-z0-9_./:@,+%=-]*) printf "'%s'" "$1" ;;
    *) printf '%s' "$1" ;;
  esac
}

# 单引号包裹无法表达值里的单引号与换行，这两种一律拒绝
env_valid_value() {
  case "$1" in
    *"'"* | *$'\n'*) return 1 ;;
  esac
  return 0
}

# env_get FILE KEY：取最后一次出现的值，去掉包裹引号与未加引号值的行尾注释；缺键返回 1
env_get() {
  local line v
  [ -f "$1" ] || return 1
  line=$(grep "^$2=" "$1" | tail -n 1)
  [ -n "$line" ] || return 1
  v="${line#*=}"
  # 整段值首尾都是同一种引号时，原样剥掉首尾各一个字符——保留内部可能出现的同类引号
  # （比如存 JSON 字符串时转义写出的 \"），不能用「找最靠左引号」的办法，否则会在内部截断。
  # 引号开头但不是这种首尾对称收尾（闭合引号后还跟了空白与行尾注释）时，才退化为剥到
  # 最靠左的同类引号为止；这两类分支必须放在这个先后顺序，前者更精确、要优先匹配
  case "$v" in
    \'*\') v="${v#\'}"; v="${v%\'}" ;;
    \"*\") v="${v#\"}"; v="${v%\"}" ;;
    \'*) v="${v#\'}"; v="${v%%\'*}" ;;
    \"*) v="${v#\"}"; v="${v%%\"*}" ;;
    *) v="${v%% #*}" ;;
  esac
  printf '%s\n' "$v"
}

# env_set FILE KEY VALUE：原地替换首个同名行并删去其余同名行；缺失则追加。
# 不重排、不动注释与其他变量；写回用 cat > 保留原文件权限与属主
env_set() {
  local f="$1" k="$2" v="$3" line tmp
  env_valid_value "$v" || return 2
  line="$k=$(env_quote "$v")"
  tmp="$f.tmp.$$"
  if [ -f "$f" ] && grep -q "^$k=" "$f"; then
    LP_LINE="$line" awk -v k="$k=" '
      index($0, k) == 1 { if (!done) { print ENVIRON["LP_LINE"]; done = 1 } next }
      { print }' "$f" >"$tmp" || { rm -f "$tmp"; return 1; }
  else
    {
      if [ -f "$f" ]; then
        cat "$f"
        [ -z "$(tail -c 1 "$f")" ] || printf '\n'
      fi
      printf '%s\n' "$line"
    } >"$tmp" || { rm -f "$tmp"; return 1; }
  fi
  if [ -f "$f" ]; then
    cat "$tmp" >"$f" && rm -f "$tmp"
  else
    mv "$tmp" "$f"
  fi
}

state_file() { printf '%s/.llamapad-state' "$LP_HOME"; }
state_get() { env_get "$(state_file)" "$1"; }
state_set() { env_set "$(state_file)" "$1" "$2"; }

_num_cmp() {
  if [ "$1" -gt "$2" ]; then echo 1; elif [ "$1" -lt "$2" ]; then echo -1; else echo 0; fi
}

# ver_cmp A B → 1 / 0 / -1。X.Y.Z 逐段数值比较；主体相同时预发布低于正式版，预发布之间按字典序
ver_cmp() {
  local a="${1#v}" b="${2#v}" ap="" bp="" r
  local a1 a2 a3 b1 b2 b3
  case "$a" in *-*) ap="${a#*-}"; a="${a%%-*}" ;; esac
  case "$b" in *-*) bp="${b#*-}"; b="${b%%-*}" ;; esac
  # 逐段剥离：缺段（如 "0.1"）时剩余段为空，下面统一补 0
  a1="${a%%.*}"; a="${a#"$a1"}"; a="${a#.}"; a2="${a%%.*}"; a="${a#"$a2"}"; a="${a#.}"; a3="${a%%.*}"
  b1="${b%%.*}"; b="${b#"$b1"}"; b="${b#.}"; b2="${b%%.*}"; b="${b#"$b2"}"; b="${b#.}"; b3="${b%%.*}"
  for r in a1 a2 a3 b1 b2 b3; do
    eval "$r=\${$r%%[!0-9]*}; $r=\${$r:-0}"
  done
  r=$(_num_cmp "$a1" "$b1"); [ "$r" = 0 ] || { echo "$r"; return; }
  r=$(_num_cmp "$a2" "$b2"); [ "$r" = 0 ] || { echo "$r"; return; }
  r=$(_num_cmp "$a3" "$b3"); [ "$r" = 0 ] || { echo "$r"; return; }
  if [ "$ap" = "$bp" ]; then
    echo 0
  elif [ -z "$ap" ]; then
    echo 1
  elif [ -z "$bp" ]; then
    echo -1
  elif [ "$(printf '%s\n%s\n' "$ap" "$bp" | sort | head -n 1)" = "$ap" ]; then
    echo -1
  else
    echo 1
  fi
}

# stdin 每行一个版本 → 输出最大的正式版（X.Y.Z）；一个都没有返回 1
ver_latest_stable() {
  local best="" v
  while IFS= read -r v; do
    v="${v#v}"
    printf '%s' "$v" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+$' || continue
    if [ -z "$best" ] || [ "$(ver_cmp "$v" "$best")" = 1 ]; then best="$v"; fi
  done
  [ -n "$best" ] || return 1
  printf '%s\n' "$best"
}

# Docker Hub tags API 的 JSON（stdin）→ 每行一个 tag 名
hub_tags_parse() {
  grep -o '"name"[[:space:]]*:[[:space:]]*"[^"]*"' | sed 's/.*"\([^"]*\)"$/\1/'
}

# ===== 5. 端口与磁盘 =====

# ss -tln / netstat -tln 的输出（stdin）里是否有该端口在监听：两者第 4 列都是「本地地址:端口」
listen_table_has_port() {
  awk -v p="$1" '{ n = split($4, a, ":"); if (a[n] == p) f = 1 } END { exit !f }'
}

# proc_tcp_has_port PORT FILE...：/proc/net/tcp{,6} 第 2 列本地地址末尾是 :十六进制端口，第 4 列 0A 为 LISTEN
proc_tcp_has_port() {
  local hex f
  hex=$(printf '%04X' "$1")
  shift
  for f in "$@"; do
    [ -r "$f" ] || continue
    awk -v h=":$hex" 'NR > 1 && $4 == "0A" && substr($2, length($2) - 4) == h { f = 1 } END { exit !f }' "$f" && return 0
  done
  return 1
}

port_in_use() {
  if command -v ss >/dev/null 2>&1; then
    ss -tln 2>/dev/null | listen_table_has_port "$1"
    return
  fi
  if command -v netstat >/dev/null 2>&1; then
    netstat -tln 2>/dev/null | listen_table_has_port "$1"
    return
  fi
  proc_tcp_has_port "$1" "$LP_PROC/net/tcp" "$LP_PROC/net/tcp6"
}

# /proc/mounts 里空格等字符写作 \040 这类八进制转义
mount_unescape() {
  printf '%b' "$(printf '%s' "$1" | sed 's/\\\([0-7][0-7][0-7]\)/\\0\1/g')"
}

# stdin 为 /proc/mounts → 输出「设备<TAB>挂载点<TAB>文件系统」。
# 过滤伪文件系统、系统目录与容器运行时目录；同一设备多处挂载（bind）只留最短的挂载点
mounts_usable() {
  awk '
    BEGIN {
      n = split("tmpfs devtmpfs overlay squashfs proc sysfs cgroup cgroup2 devpts mqueue securityfs debugfs tracefs pstore bpf autofs hugetlbfs configfs fusectl rpc_pipefs nsfs efivarfs binfmt_misc ramfs fuse.lxcfs nfsd", x, " ")
      for (i = 1; i <= n; i++) skip[x[i]] = 1
    }
    skip[$3] { next }
    $2 ~ /^\/(boot|proc|sys|dev|run|snap)(\/|$)/ { next }
    $2 ~ /^\/var\/lib\/(docker|containerd|kubelet)(\/|$)/ { next }
    { if (!($1 in best) || length($2) < length(best[$1])) { best[$1] = $2; fs[$1] = $3 } }
    END { for (d in best) printf "%s\t%s\t%s\n", d, best[d], fs[d] }'
}

# nvme0n1p2→nvme0n1、mmcblk0p1→mmcblk0、sda3→sda。
# 这一支要求「数字+p+数字」结尾才算分区后缀：loop0 本身以 p 收尾的假分区不能被误剥成 loo
disk_strip_part() {
  case "$1" in
    nvme* | mmcblk* | loop*) printf '%s' "$1" | sed -E 's/([0-9])p[0-9]+$/\1/' ;;
    *) printf '%s' "$1" | sed -E 's/[0-9]+$//' ;;
  esac
}

# 块设备名 → nvme / ssd / hdd / mixed / unknown。
# 虚拟盘（vd*、xvd*）的 rotational 常误报为 1，宁可 unknown 也不标 HDD 误导用户
disk_type_of_block() {
  local name="$1" base s t types=""
  case "$name" in
    dm-* | md*)
      [ -d "$LP_SYSFS/block/$name/slaves" ] || { printf unknown; return; }
      for s in "$LP_SYSFS/block/$name/slaves"/*; do
        [ -e "$s" ] || [ -L "$s" ] || continue
        t=$(disk_type_of_block "$(basename "$s")")
        case " $types " in
          *" $t "*) ;;
          *) types="$types $t" ;;
        esac
      done
      types="${types# }"
      case "$types" in
        "") printf unknown ;;
        *" "*) printf mixed ;;
        *) printf '%s' "$types" ;;
      esac
      return
      ;;
  esac
  base="$name"
  [ -d "$LP_SYSFS/block/$base" ] || base=$(disk_strip_part "$name")
  case "$base" in
    nvme*) printf nvme ;;
    vd* | xvd*) printf unknown ;;
    *)
      case "$(cat "$LP_SYSFS/block/$base/queue/rotational" 2>/dev/null)" in
        1) printf hdd ;;
        0) printf ssd ;;
        *) printf unknown ;;
      esac
      ;;
  esac
}

# disk_type 设备 文件系统 → nvme / ssd / hdd / mixed / network / unknown
disk_type() {
  local dev="$1" fs="$2" d
  case "$fs" in
    nfs* | cifs | smb* | fuse.sshfs | glusterfs | ceph) printf network; return ;;
  esac
  case "$dev" in
    /dev/mapper/*)
      for d in "$LP_SYSFS"/block/dm-*; do
        if [ "$(cat "$d/dm/name" 2>/dev/null)" = "${dev#/dev/mapper/}" ]; then
          disk_type_of_block "$(basename "$d")"
          return
        fi
      done
      printf unknown
      ;;
    /dev/*) disk_type_of_block "${dev#/dev/}" ;;
    *) printf unknown ;;
  esac
}

# 路径不存在时向上找到第一个已存在的祖先（df 只能查存在的路径）
path_existing_parent() {
  local p="$1"
  while [ ! -e "$p" ] && [ "$p" != / ]; do p=$(dirname "$p"); done
  printf '%s' "$p"
}

df_avail_kb() {
  df -Pk "$1" 2>/dev/null | awk 'NR == 2 { print $4; f = 1 } END { exit !f }'
}

# 挂载点在第 6 列之后（含空格的挂载点会被 awk 拆开，这里把第 6 列起的内容拼回）
df_mount() {
  df -Pk "$1" 2>/dev/null | awk 'NR == 2 { $1 = $2 = $3 = $4 = $5 = ""; sub(/^ +/, ""); print }'
}

# disk_candidates 默认路径 → TSV「路径<TAB>盘类型<TAB>剩余KB<TAB>是否系统盘」。
# 首行是默认位置（类型取其所在挂载点），其余每个可用挂载点给出 <挂载点>/llamapad/models，按剩余空间降序
disk_candidates() {
  local def="$1" defparent defmount deftype=unknown tab dev mnt fs avail rows=""
  tab=$(printf '\t')
  defparent=$(path_existing_parent "$def")
  defmount=$(df_mount "$defparent")
  while IFS="$tab" read -r dev mnt fs; do
    [ -n "$dev" ] || continue
    mnt=$(mount_unescape "$mnt")
    if [ "$mnt" = "$defmount" ]; then
      deftype=$(disk_type "$dev" "$fs")
      continue
    fi
    avail=$(df_avail_kb "$mnt") || continue
    rows="$rows${mnt%/}/llamapad/models$tab$(disk_type "$dev" "$fs")$tab$avail${tab}0
"
  done <<EOF
$(mounts_usable <"$LP_PROC/mounts")
EOF
  printf '%s\t%s\t%s\t%s\n' "$def" "$deftype" "$(df_avail_kb "$defparent")" "$([ "$defmount" = / ] && echo 1 || echo 0)"
  printf '%s' "$rows" | sort -t "$tab" -k3,3nr
}

# ===== 6. 环境探测 =====

lp_is_root() { [ "$(id -u)" = 0 ]; }

# 以 root 身份执行：已是 root 直接跑，否则经 sudo；都不行时报错
as_root() {
  if lp_is_root; then
    "$@"
    return
  fi
  if command -v "$LP_SUDO" >/dev/null 2>&1; then
    "$LP_SUDO" "$@"
    return
  fi
  err "$(t need_root)"
  return 1
}

platform_ok() {
  [ "${LLAMAPAD_SKIP_PLATFORM_CHECK:-}" = 1 ] || [ "$(uname -s)" = Linux ]
}

DK_SUDO=0
DK_STATE=""

# 所有 docker 调用都经它：探测出需要 sudo 时自动加上
dk() {
  if [ "$DK_SUDO" = 1 ]; then
    "$LP_SUDO" "$LP_DOCKER" "$@"
  else
    "$LP_DOCKER" "$@"
  fi
}

# 设置 DK_STATE：ok / missing / daemon_down / rootless / no_compose，非 ok 返回 1
docker_probe() {
  DK_SUDO=0
  if ! command -v "$LP_DOCKER" >/dev/null 2>&1; then
    DK_STATE=missing
    return 1
  fi
  if ! "$LP_DOCKER" info >/dev/null 2>&1; then
    # 连不上有两种可能：没权限访问 sock（非 root 且不在 docker 组），或 daemon 根本没起
    if [ -S "$LP_DOCKER_SOCK" ] && ! lp_is_root &&
      { [ ! -r "$LP_DOCKER_SOCK" ] || [ ! -w "$LP_DOCKER_SOCK" ]; } &&
      command -v "$LP_SUDO" >/dev/null 2>&1; then
      info "$(t docker_sudo_note)"
      DK_SUDO=1
      if ! dk info >/dev/null 2>&1; then
        DK_STATE=daemon_down
        return 1
      fi
    else
      DK_STATE=daemon_down
      return 1
    fi
  fi
  case "$(dk info --format '{{.SecurityOptions}}' 2>/dev/null)" in
    *rootless*) DK_STATE=rootless; return 1 ;;
  esac
  if ! dk compose version >/dev/null 2>&1; then
    DK_STATE=no_compose
    return 1
  fi
  DK_STATE=ok
}

docker_probe_message() {
  case "$DK_STATE" in
    missing) t docker_missing ;;
    daemon_down) t docker_daemon_down ;;
    rootless) t docker_rootless ;;
    no_compose) t docker_no_compose ;;
    *) t docker_unknown ;;
  esac
}

require_docker() {
  docker_probe && return 0
  err "$(docker_probe_message)"
  return 1
}

detect_docker_gid() {
  stat -c %g "$LP_DOCKER_SOCK" 2>/dev/null || stat -f %g "$LP_DOCKER_SOCK" 2>/dev/null
}

# 每行一张卡「GPU N: 型号」；nvidia-smi 不存在或无卡时返回 1
gpu_cards() {
  command -v "$LP_NVIDIA_SMI" >/dev/null 2>&1 || return 1
  "$LP_NVIDIA_SMI" -L 2>/dev/null | grep '^GPU ' | sed -E 's/ \(UUID: [^)]*\)$//'
}

# 容器能否用 GPU：docker 注册了 nvidia 运行时，或 nvidia-container-toolkit 生成了 CDI 规格
gpu_runtime_ok() {
  dk info --format '{{json .Runtimes}}' 2>/dev/null | grep -q nvidia && return 0
  [ -f "$LP_ETC/cdi/nvidia.yaml" ] || [ -f /var/run/cdi/nvidia.yaml ]
}

detect_timezone() {
  local tz="" link
  [ -f "$LP_ETC/timezone" ] && tz=$(head -n 1 "$LP_ETC/timezone")
  [ -n "$tz" ] || tz=$(timedatectl show -p Timezone --value 2>/dev/null)
  if [ -z "$tz" ] && [ -L "$LP_ETC/localtime" ]; then
    link=$(readlink "$LP_ETC/localtime")
    case "$link" in
      *zoneinfo/*) tz="${link##*zoneinfo/}" ;;
    esac
  fi
  printf '%s' "${tz:-UTC}"
}

lan_ips() {
  local ips
  ips=$(hostname -I 2>/dev/null)
  [ -n "$ips" ] || ips=$(ip -4 -o addr show scope global 2>/dev/null | awk '{ sub(/\/.*/, "", $4); print $4 }')
  # shellcheck disable=SC2086
  printf '%s\n' $ips | grep -E '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$' | head -n 3
}

# access_urls 监听地址 端口 → 每行一个可访问地址
access_urls() {
  local ip
  case "$1" in
    "" | 0.0.0.0)
      for ip in $(lan_ips) 127.0.0.1; do printf 'http://%s:%s\n' "$ip" "$2"; done
      ;;
    *) printf 'http://%s:%s\n' "$1" "$2" ;;
  esac
}

# ===== 7. 终端交互 =====

# 交互输出一律写 stderr；按键一律从 $LP_TTY 读（curl | bash 时 stdin 是管道，不能读 stdin）

# 数字菜单模式：显式要求、哑终端、stderr 不是终端、或打不开 TTY
ui_plain() {
  [ "${LLAMAPAD_PLAIN:-}" = 1 ] && return 0
  [ "${TERM:-dumb}" = dumb ] && return 0
  [ -t 2 ] || return 0
  { : <"$LP_TTY"; } 2>/dev/null || return 0
  return 1
}

LP_STTY_SAVED=""

# 进入菜单：关回显与行缓冲、隐藏光标、关自动换行（超长行被终端截断而不是折行，重绘行数才算得准）
ui_raw_on() {
  LP_STTY_SAVED=$(stty -g <"$LP_TTY" 2>/dev/null)
  stty -echo -icanon <"$LP_TTY" 2>/dev/null
  printf '\033[?25l\033[?7l' >&2
}

ui_raw_off() {
  if [ -n "$LP_STTY_SAVED" ]; then
    stty "$LP_STTY_SAVED" <"$LP_TTY" 2>/dev/null
    LP_STTY_SAVED=""
  fi
  printf '\033[?25h\033[?7h' >&2
}

# 退出 / 中断时恢复终端（由 main 挂到 trap）
ui_restore() {
  if [ -n "$LP_STTY_SAVED" ]; then ui_raw_off; fi
}

# 读一个按键 → up / down / left / right / enter / backspace / char:<字符>。
# 方向键是 ESC [ X（或 ESC O X）三字节：读到 ESC 再读两字节。不支持单按 ESC（会阻塞等待后续字节）
ui_read_key() {
  local k rest
  IFS= read -rsn1 k <"$LP_TTY" || return 1
  case "$k" in
    $'\033')
      IFS= read -rsn2 rest <"$LP_TTY"
      case "$rest" in
        "[A" | OA) echo up ;;
        "[B" | OB) echo down ;;
        "[C" | OC) echo right ;;
        "[D" | OD) echo left ;;
        *) echo other ;;
      esac
      ;;
    "") echo enter ;;
    $'\177' | $'\010') echo backspace ;;
    *) printf 'char:%s\n' "$k" ;;
  esac
}

# ui_menu 标题 选项... → UI_CHOICE（0 起）；q 或输入结束返回 1。UI_DEFAULT 可预设初始选中项（用后清零）
ui_menu() {
  local title="$1" n sel key i ans
  shift
  n=$#
  sel="${UI_DEFAULT:-0}"
  UI_DEFAULT=0
  if ui_plain; then
    printf '%s\n' "$title" >&2
    i=1
    for ans in "$@"; do
      printf '  %d) %s\n' "$i" "$ans" >&2
      i=$((i + 1))
    done
    while :; do
      printf '%s' "$(t ui_number_prompt)" >&2
      IFS= read -r ans <"$LP_TTY" || return 1
      case "$ans" in
        q | Q) return 1 ;;
        "" | *[!0-9]*) continue ;;
      esac
      if [ "$ans" -ge 1 ] && [ "$ans" -le "$n" ]; then
        UI_CHOICE=$((ans - 1))
        return 0
      fi
    done
  fi
  ui_raw_on
  printf '%s\n' "$title" >&2
  _ui_menu_draw "$sel" "$@"
  while :; do
    key=$(ui_read_key) || { ui_raw_off; return 1; }
    case "$key" in
      up | char:k) sel=$(((sel + n - 1) % n)) ;;
      down | char:j) sel=$(((sel + 1) % n)) ;;
      enter) break ;;
      char:q | char:Q) ui_raw_off; return 1 ;;
      *) continue ;;
    esac
    printf '\033[%dA' "$((n + 1))" >&2
    _ui_menu_draw "$sel" "$@"
  done
  ui_raw_off
  UI_CHOICE=$sel
}

_ui_menu_draw() {
  local sel="$1" i=0 o
  shift
  for o in "$@"; do
    if [ "$i" = "$sel" ]; then
      printf '\r\033[K  %s▶ %s%s\n' "$(lp_sgr '1;36')" "$o" "$(lp_sgr 0)" >&2
    else
      printf '\r\033[K    %s\n' "$o" >&2
    fi
    i=$((i + 1))
  done
  printf '\r\033[K  %s%s%s\n' "$(lp_sgr 2)" "$(t ui_menu_hint)" "$(lp_sgr 0)" >&2
}

# ui_input 提示 默认值 → UI_VALUE。终端模式支持 ←→ 移动光标与退格（按字节计，面向 ASCII 路径与数字）
ui_input() {
  local prompt="$1" def="${2:-}" buf pos key ch
  if ui_plain; then
    if [ -n "$def" ]; then printf '%s [%s]: ' "$prompt" "$def" >&2; else printf '%s: ' "$prompt" >&2; fi
    IFS= read -r buf <"$LP_TTY" || return 1
    UI_VALUE="${buf:-$def}"
    return 0
  fi
  buf="$def"
  pos=${#buf}
  LP_STTY_SAVED=$(stty -g <"$LP_TTY" 2>/dev/null)
  stty -echo -icanon <"$LP_TTY" 2>/dev/null
  while :; do
    printf '\r\033[K%s: %s' "$prompt" "$buf" >&2
    if [ "$pos" -lt "${#buf}" ]; then printf '\033[%dD' "$((${#buf} - pos))" >&2; fi
    key=$(ui_read_key) || { ui_raw_off; return 1; }
    case "$key" in
      enter) break ;;
      left) [ "$pos" -gt 0 ] && pos=$((pos - 1)) ;;
      right) [ "$pos" -lt "${#buf}" ] && pos=$((pos + 1)) ;;
      backspace)
        if [ "$pos" -gt 0 ]; then
          buf="${buf:0:pos-1}${buf:pos}"
          pos=$((pos - 1))
        fi
        ;;
      char:*)
        ch="${key#char:}"
        buf="${buf:0:pos}${ch}${buf:pos}"
        pos=$((pos + 1))
        ;;
    esac
  done
  printf '\n' >&2
  ui_raw_off
  UI_VALUE="$buf"
}

# ui_password 提示 → UI_VALUE（不回显）
ui_password() {
  local p
  printf '%s: ' "$1" >&2
  IFS= read -rs p <"$LP_TTY" || { printf '\n' >&2; return 1; }
  printf '\n' >&2
  UI_VALUE="$p"
}

_ui_btn() {
  if [ "$2" = 1 ]; then
    printf '%s[ %s ]%s' "$(lp_sgr '1;7')" "$1" "$(lp_sgr 0)"
  else
    printf '  %s  ' "$1"
  fi
}

# ui_confirm 提示 [y|n 默认] → 0 是 / 1 否。终端模式「是 / 否」横排，←→ 切换，也可直接按 y / n
ui_confirm() {
  local prompt="$1" def="${2:-y}" sel key ans
  if ui_plain; then
    while :; do
      if [ "$def" = y ]; then printf '%s (Y/n) ' "$prompt" >&2; else printf '%s (y/N) ' "$prompt" >&2; fi
      IFS= read -r ans <"$LP_TTY" || return 1
      case "${ans:-$def}" in
        y | Y | yes | YES | 是) return 0 ;;
        n | N | no | NO | 否) return 1 ;;
      esac
    done
  fi
  if [ "$def" = y ]; then sel=0; else sel=1; fi
  ui_raw_on
  while :; do
    printf '\r\033[K%s  %s %s' "$prompt" "$(_ui_btn "$(t ui_yes)" "$([ "$sel" = 0 ] && echo 1)")" \
      "$(_ui_btn "$(t ui_no)" "$([ "$sel" = 1 ] && echo 1)")" >&2
    key=$(ui_read_key) || { ui_raw_off; return 1; }
    case "$key" in
      left | right | char:h | char:l) sel=$((1 - sel)) ;;
      char:y | char:Y) sel=0; break ;;
      char:n | char:N) sel=1; break ;;
      enter) break ;;
    esac
  done
  printf '\n' >&2
  ui_raw_off
  [ "$sel" = 0 ]
}

ui_pause() {
  local _
  printf '%s' "$(t ui_press_enter)" >&2
  IFS= read -r _ <"$LP_TTY"
}

# ===== 8. 模板与写入 =====

# 内嵌模板：必须与 deploy/docker-compose.yml、deploy/docker-compose.gpu.yml 逐字节一致（测试守护），
# 改模板时两边同改，并把 LLAMAPAD_TEMPLATE_VERSION 加 1
tpl_compose() {
  cat <<'LLAMAPAD_COMPOSE_EOF'
# llamapad 部署编排。可变项全部在同目录 .env 里（llamapad.sh 生成并维护，也可手改），
# 本文件通常无需改动；GPU 叠加层见 docker-compose.gpu.yml，由 .env 的 COMPOSE_FILE 启用。
services:
  llamapad:
    image: lancelrq/llamapad:${LLAMAPAD_VERSION:?请在 .env 设置 LLAMAPAD_VERSION}
    container_name: llamapad
    restart: unless-stopped
    # 运行身份：面板要写 data 与模型库两个 bind 目录，容器内用户必须对它们可写
    user: "${PUID:-1000}:${PGID:-1000}"
    # 端口取在内核临时端口段（Linux 常见 32768-60999）下方，避免与出站连接抢端口；
    # 置于 HTTPS 反代之后时把 PANEL_BIND 设为 127.0.0.1，面板就不会直接暴露在网络上
    ports:
      - "${PANEL_BIND:-0.0.0.0}:${PANEL_PORT:-28960}:28960"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/config
      # 模型库宿主机路径不必另行告知面板：面板经 docker.sock 查自身挂载表自动识别
      - ${MODELS_DIR:-./models}:/host-models
      # 宿主机网络指标：容器有独立网络命名空间，读 PID 1 的 netns 才是宿主机网卡；
      # 不挂此项时只有网络收发速率两项缺省，其余指标照常
      - /proc:/host/proc:ro
    environment:
      - PANEL_DOCKER=real
      - TZ=${TZ:-Asia/Shanghai}
      - PANEL_CONFIG=/app/config/panel.yaml
      - PANEL_DB=/app/config/panel.db
      # 管理员密码唯一来源：面板启动时与库内不一致即更新，并让全部登录会话失效
      - PANEL_ADMIN_PASSWORD=${PANEL_ADMIN_PASSWORD:?请在 .env 设置 PANEL_ADMIN_PASSWORD}
      - PANEL_LLAMA_HOST=host.docker.internal
      # 外部 LLM（可选，OpenAI 兼容）：README 推荐参数的 AI 解析，留空即未配置
      - PANEL_LLM_BASE_URL=${PANEL_LLM_BASE_URL:-}
      - PANEL_LLM_API_KEY=${PANEL_LLM_API_KEY:-}
      - PANEL_LLM_MODEL=${PANEL_LLM_MODEL:-}
      - PANEL_LLM_EXTRA_BODY=${PANEL_LLM_EXTRA_BODY:-}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # docker.sock 的 gid 因机器而异；llamapad.sh 每次启动自动探测并写回 .env
    group_add:
      - "${DOCKER_GID:?请在 .env 设置 DOCKER_GID（stat -c %g /var/run/docker.sock）}"
LLAMAPAD_COMPOSE_EOF
}

tpl_compose_gpu() {
  cat <<'LLAMAPAD_GPU_EOF'
# GPU 叠加层：.env 的 COMPOSE_FILE 含本文件时生效（llamapad.sh 按探测结果设置）。
# 面板容器内 nvidia-smi 靠它做显存监控；模型容器的 GPU 参数由面板按模型配置单独传入
services:
  llamapad:
    gpus: all
LLAMAPAD_GPU_EOF
}

compose_file_value() {
  if [ "$1" = 1 ]; then
    printf 'docker-compose.yml:docker-compose.gpu.yml'
  else
    printf 'docker-compose.yml'
  fi
}

# MODELS_DIR 可以是相对路径（相对部署目录，compose 也是这么解析的）
models_abs() {
  case "$1" in
    /*) printf '%s' "$1" ;;
    "") printf '%s/models' "$LP_HOME" ;;
    *) printf '%s/%s' "$LP_HOME" "${1#./}" ;;
  esac
}

# 向导答案（W_*）的默认值；安装、接管、修改配置共用这组变量
wizard_defaults() {
  W_VERSION="$LLAMAPAD_SCRIPT_VERSION"
  W_MODELS_DIR=""
  W_MODELS_NEW=0
  W_PUID=1000
  W_PGID=1000
  W_GPU=0
  W_PORT="$LLAMAPAD_DEFAULT_PORT"
  W_BIND=0.0.0.0
  W_PASSWORD=""
  W_PASSWORD_GENERATED=0
  W_TZ=UTC
  W_DOCKER_GID=""
  W_LLM_BASE_URL=""
  W_LLM_API_KEY=""
  W_LLM_MODEL=""
}

env_header() {
  printf '%s\n%s\n\n' "$(t env_header_1)" "$(t env_header_2)"
}

# 把 W_* 按键写入 .env（原地替换，保留文件其余内容）
write_env_values() {
  local f="$1"
  env_set "$f" LLAMAPAD_VERSION "$W_VERSION" &&
    env_set "$f" COMPOSE_FILE "$(compose_file_value "$W_GPU")" &&
    env_set "$f" PANEL_ADMIN_PASSWORD "$W_PASSWORD" &&
    env_set "$f" DOCKER_GID "$W_DOCKER_GID" &&
    env_set "$f" PUID "$W_PUID" &&
    env_set "$f" PGID "$W_PGID" &&
    env_set "$f" PANEL_BIND "$W_BIND" &&
    env_set "$f" PANEL_PORT "$W_PORT" &&
    env_set "$f" MODELS_DIR "$W_MODELS_DIR" &&
    env_set "$f" TZ "$W_TZ" &&
    env_set "$f" PANEL_LLM_BASE_URL "$W_LLM_BASE_URL" &&
    env_set "$f" PANEL_LLM_API_KEY "$W_LLM_API_KEY" &&
    env_set "$f" PANEL_LLM_MODEL "$W_LLM_MODEL"
}

# 写两个 compose 文件并把校验和记进 state，升级时据此判断用户是否手改过
write_templates() {
  tpl_compose >"$LP_HOME/docker-compose.yml" || return 1
  tpl_compose_gpu >"$LP_HOME/docker-compose.gpu.yml" || return 1
  state_set compose_sha256 "$(sha256_file "$LP_HOME/docker-compose.yml")" &&
    state_set gpu_compose_sha256 "$(sha256_file "$LP_HOME/docker-compose.gpu.yml")" &&
    state_set template_version "$LLAMAPAD_TEMPLATE_VERSION"
}

# fix_owner 目录 UID GID：属主不符时改（先直接改，没权限再提权）
fix_owner() {
  [ "$(stat_owner "$1")" = "$2:$3" ] && return 0
  chown -R "$2:$3" "$1" 2>/dev/null && return 0
  info "$(t chown_need_root "$1" "$2:$3")"
  as_root chown -R "$2:$3" "$1"
}

ensure_models_dir() {
  local d
  d=$(models_abs "$W_MODELS_DIR")
  if [ ! -d "$d" ]; then
    if ! mkdir -p "$d" 2>/dev/null; then
      info "$(t mkdir_need_root "$d")"
      as_root mkdir -p "$d" || return 1
    fi
  fi
  # 只对本次新建的空目录对齐属主；既有模型库动辄上百 GB，绝不 chown
  if [ "$W_MODELS_NEW" = 1 ]; then
    fix_owner "$d" "$W_PUID" "$W_PGID"
  fi
}

# 按 W_* 写出全部部署文件（全新安装与修改后重写共用）。
# state（尤其 installed_at/template_version）必须最后写：入口靠「state 文件存在」判定目录已安装，
# 一旦模型库建不起来之类的步骤半路失败却已经落了 state，重跑会被误判成已安装直接跳过向导
apply_install() {
  local envf="$LP_HOME/.env"
  mkdir -p "$LP_HOME/data" "$LP_HOME/backups" || return 1
  ensure_models_dir || return 1
  fix_owner "$LP_HOME/data" "$W_PUID" "$W_PGID" || return 1
  write_templates || return 1
  [ -f "$envf" ] || env_header >"$envf" || return 1
  chmod 600 "$envf" || return 1
  write_env_values "$envf" || return 1
  state_set installed_at "$(date -u +%Y-%m-%dT%H:%M:%SZ)" || return 1
}

# ===== 9. 安装与向导 =====

# dir_state 目录 → installed / adopt / empty
dir_state() {
  if [ -f "$1/.llamapad-state" ]; then
    printf installed
  elif [ -f "$1/docker-compose.yml" ] || [ -f "$1/.env" ]; then
    printf adopt
  else
    printf empty
  fi
}

# 部署目录候选：--dir > LLAMAPAD_HOME（命令入口设置）> 脚本自身所在目录
home_candidate() {
  if [ -n "$OPT_DIR" ]; then
    abs_path "$OPT_DIR"
  elif [ -n "${LLAMAPAD_HOME:-}" ]; then
    abs_path "$LLAMAPAD_HOME"
  elif [ -n "$LP_SELF" ] && [ -f "$LP_SELF" ]; then
    abs_path "$(dirname "$LP_SELF")"
  fi
}

# 命令入口是两行启动器而非符号链接：安装目录写死在里面，任意目录执行都作用于它，
# 也不依赖 readlink -f 解析链接（busybox 等精简环境同样可用）
launcher_content() {
  printf '#!/bin/sh\nexport LLAMAPAD_HOME=%s\nexec %s "$@"\n' "$(sh_quote "$1")" "$(sh_quote "$1/llamapad.sh")"
}

install_launcher() {
  local home="$1" dst="$LP_BIN_DIR/llamapad" tmp
  if [ -f "$dst" ] && ! grep -qF "$(sh_quote "$home/llamapad.sh")" "$dst"; then
    if ! ui_confirm "$(t launcher_overwrite "$dst")" n; then
      warn "$(t launcher_skipped "$home/llamapad.sh")"
      return 0
    fi
  fi
  tmp="$home/.llamapad-launcher.tmp"
  launcher_content "$home" >"$tmp" && chmod 755 "$tmp" || return 1
  if [ -d "$LP_BIN_DIR" ] && [ -w "$LP_BIN_DIR" ]; then
    mv "$tmp" "$dst" || { rm -f "$tmp"; return 1; }
  else
    if ! ui_confirm "$(t launcher_need_sudo "$dst")" y ||
      ! { as_root mkdir -p "$LP_BIN_DIR" && as_root mv "$tmp" "$dst"; }; then
      rm -f "$tmp"
      warn "$(t launcher_skipped "$home/llamapad.sh")"
      return 0
    fi
  fi
  ok "$(t launcher_done "$dst")"
}

raw_url() {
  printf '%s/%s/deploy/llamapad.sh' "$LP_RAW_BASE" "$1"
}

# download_to 地址 文件 [超时秒]
download_to() {
  local to="${3:-30}"
  if command -v curl >/dev/null 2>&1; then
    curl -fsSL --connect-timeout 10 --max-time "$to" -o "$2" "$1" 2>/dev/null
  elif command -v wget >/dev/null 2>&1; then
    wget -q -T "$to" -O "$2" "$1" 2>/dev/null
  else
    return 127
  fi
}

# 把脚本本体放进安装目录：真实文件运行时复制自身；curl | bash 时读不到自身，
# 按自身版本的 tag 重新下载（tag 未发布时回退 main），过了 bash -n 才落盘
place_self() {
  local home="$1" dst="$1/llamapad.sh" tmp="$1/.llamapad.sh.tmp"
  if [ -n "$LP_SELF" ] && [ -f "$LP_SELF" ]; then
    [ "$(abs_path "$LP_SELF")" = "$dst" ] && return 0
    cp "$LP_SELF" "$tmp" || return 1
  elif ! download_to "$(raw_url "v$LLAMAPAD_SCRIPT_VERSION")" "$tmp" &&
    ! download_to "$(raw_url main)" "$tmp"; then
    rm -f "$tmp"
    err "$(t self_download_failed)"
    return 1
  fi
  if ! bash -n "$tmp" 2>/dev/null; then
    rm -f "$tmp"
    err "$(t self_syntax_failed)"
    return 1
  fi
  chmod 755 "$tmp" && mv "$tmp" "$dst"
}

ensure_dir_writable() {
  local d="$1"
  mkdir -p "$d" 2>/dev/null
  [ -d "$d" ] && [ -w "$d" ] && return 0
  ui_confirm "$(t dir_need_root "$d")" y || return 1
  as_root mkdir -p "$d" && as_root chown "$(id -u):$(id -g)" "$d"
}

disk_type_label() {
  t "disk_type_$1"
}

valid_models_path() {
  case "$1" in /*) ;; *) return 1 ;; esac
  case "$1" in *[[:space:]:\'\"]*) return 1 ;; esac
  return 0
}

models_report() {
  local n size
  n=$(find "$1" -name '*.gguf' -type f 2>/dev/null | wc -l | tr -d ' ')
  [ "${n:-0}" -gt 0 ] || return 0
  size=$(du -sk "$1" 2>/dev/null | awk '{print $1}')
  info "$(t models_found "$n" "$(fmt_kb "${size:-0}")")"
}

# 设置 W_MODELS_DIR、W_MODELS_NEW
choose_models_dir() {
  local def="$LP_HOME/models" tab rows p type avail sys label
  local paths=() labels=()
  tab=$(printf '\t')
  rows=$(disk_candidates "$def")
  while IFS="$tab" read -r p type avail sys; do
    [ -n "$p" ] || continue
    label=$(printf '%-40s %-8s %s' "$p" "$(disk_type_label "$type")" "$(t disk_free "$(fmt_kb "$avail")")")
    [ "$sys" = 1 ] && label="$label  $(t disk_system)"
    [ "${avail:-0}" -lt "$LLAMAPAD_MIN_FREE_KB" ] && label="$label  $(t disk_low_space)"
    [ "$type" = network ] && label="$label  $(t disk_network_slow)"
    paths+=("$p")
    labels+=("$label")
  done <<EOF
$rows
EOF
  labels+=("$(t disk_manual)")
  ui_menu "$(t ask_models_dir)" "${labels[@]}" || return 1
  if [ "$UI_CHOICE" -lt "${#paths[@]}" ]; then
    p="${paths[$UI_CHOICE]}"
  else
    while :; do
      ui_input "$(t ask_models_path)" "$def" || return 1
      # 先拦相对路径再转绝对：否则 abs_path 会把它静默拼到当前目录下
      # shellcheck disable=SC2088  # case 模式匹配字面量 "~"/"~/"*，不是期待展开的命令参数，误报
      case "$UI_VALUE" in
        /* | "~" | "~/"*) p=$(abs_path "$UI_VALUE") ;;
        *) p="" ;;
      esac
      valid_models_path "$p" && break
      warn "$(t models_path_invalid)"
    done
  fi
  W_MODELS_DIR="$p"
  if [ -d "$p" ]; then
    W_MODELS_NEW=0
    models_report "$p"
  else
    W_MODELS_NEW=1
  fi
}

# 设置 W_PUID、W_PGID
choose_identity() {
  local cur owner="" v
  cur="$(id -u):$(id -g)"
  if [ "$W_MODELS_NEW" = 0 ] && [ -d "$(models_abs "$W_MODELS_DIR")" ]; then
    owner=$(stat_owner "$(models_abs "$W_MODELS_DIR")")
    ui_menu "$(t ask_identity)" "$(t identity_follow "$owner")" "$(t identity_current "$cur")" \
      "$(t identity_root)" "$(t identity_custom)" || return 1
  else
    owner="1000:1000"
    ui_menu "$(t ask_identity)" "$(t identity_new)" "$(t identity_current "$cur")" \
      "$(t identity_root)" "$(t identity_custom)" || return 1
  fi
  case "$UI_CHOICE" in
    0) v="$owner" ;;
    1) v="$cur" ;;
    2) v="0:0" ;;
    *)
      while :; do
        ui_input "$(t ask_uid_gid)" "$owner" || return 1
        v="$UI_VALUE"
        printf '%s' "$v" | grep -Eq '^[0-9]+:[0-9]+$' && break
        warn "$(t uid_gid_invalid)"
      done
      ;;
  esac
  W_PUID="${v%%:*}"
  W_PGID="${v#*:}"
}

# 设置 W_GPU
choose_gpu() {
  local cards
  cards=$(gpu_cards)
  if [ -z "$cards" ]; then
    info "$(t gpu_none)"
    W_GPU=0
    return 0
  fi
  info "$(t gpu_found)"
  printf '%s\n' "$cards" | sed 's/^/    /' >&2
  if gpu_runtime_ok; then
    if ui_confirm "$(t ask_gpu_enable)" y; then W_GPU=1; else W_GPU=0; fi
  else
    warn "$(t gpu_no_toolkit)"
    if ui_confirm "$(t ask_gpu_enable_anyway)" n; then W_GPU=1; else W_GPU=0; fi
  fi
}

valid_port() {
  case "$1" in "" | *[!0-9]*) return 1 ;; esac
  [ "$1" -ge 1 ] && [ "$1" -le 65535 ]
}

# 设置 W_PORT；可传入一个「允许占用」的端口（修改配置时面板自己正占着当前端口）
choose_port() {
  local allow="${1:-}" p
  while :; do
    ui_input "$(t ask_port)" "$W_PORT" || return 1
    p="$UI_VALUE"
    if ! valid_port "$p"; then
      warn "$(t port_invalid)"
      continue
    fi
    if [ "$p" != "$allow" ] && port_in_use "$p"; then
      warn "$(t port_busy "$p")"
      continue
    fi
    W_PORT="$p"
    return 0
  done
}

valid_ipv4() {
  printf '%s' "$1" | grep -Eq '^([0-9]{1,3}\.){3}[0-9]{1,3}$' || return 1
  local IFS=. o
  # shellcheck disable=SC2086
  set -- $1
  for o in "$@"; do [ "$o" -le 255 ] || return 1; done
}

# 设置 W_BIND
choose_bind() {
  ui_menu "$(t ask_bind)" "$(t bind_all)" "$(t bind_local)" "$(t bind_custom)" || return 1
  case "$UI_CHOICE" in
    0) W_BIND=0.0.0.0 ;;
    1) W_BIND=127.0.0.1 ;;
    *)
      while :; do
        ui_input "$(t ask_bind_ip)" "" || return 1
        valid_ipv4 "$UI_VALUE" && break
        warn "$(t bind_invalid)"
      done
      W_BIND="$UI_VALUE"
      ;;
  esac
}

# 设置 W_PASSWORD、W_PASSWORD_GENERATED
choose_password() {
  local a
  while :; do
    ui_password "$(t ask_password)" || return 1
    a="$UI_VALUE"
    if [ -z "$a" ]; then
      W_PASSWORD=$(gen_password 20)
      W_PASSWORD_GENERATED=1
      return 0
    fi
    if [ "${#a}" -lt 8 ]; then
      warn "$(t password_too_short)"
      continue
    fi
    if ! env_valid_value "$a"; then
      warn "$(t password_bad_char)"
      continue
    fi
    ui_password "$(t ask_password_again)" || return 1
    if [ "$a" != "$UI_VALUE" ]; then
      warn "$(t password_mismatch)"
      continue
    fi
    W_PASSWORD="$a"
    W_PASSWORD_GENERATED=0
    return 0
  done
}

# 设置 W_TZ
choose_timezone() {
  while :; do
    ui_input "$(t ask_timezone)" "$W_TZ" || return 1
    # 含单引号的值 env_set 会拒绝写入（单引号包裹表达不了），与空值、含空格一并在这里挡掉
    case "$UI_VALUE" in
      "" | *[[:space:]]* | *"'"*) warn "$(t timezone_invalid)" ;;
      *) W_TZ="$UI_VALUE"; return 0 ;;
    esac
  done
}

# ui_input_valid 提示 默认值 → UI_VALUE；含单引号或换行的值 env_set 会拒绝写入且不报错，
# 在这里挡在入口处重问，好过让 cmd_config 各分支在写入失败后各自补提示
ui_input_valid() {
  while :; do
    ui_input "$1" "$2" || return 1
    env_valid_value "$UI_VALUE" && return 0
    warn "$(t value_bad_char)"
  done
}

# choose_llm [force]：安装向导先问是否配置；修改配置时传 force 直接进入输入
choose_llm() {
  if [ "${1:-}" != force ] && ! ui_confirm "$(t ask_llm)" n; then
    return 0
  fi
  ui_input_valid "$(t ask_llm_base_url)" "$W_LLM_BASE_URL" || return 1
  W_LLM_BASE_URL="$UI_VALUE"
  ui_input_valid "$(t ask_llm_api_key)" "$W_LLM_API_KEY" || return 1
  W_LLM_API_KEY="$UI_VALUE"
  ui_input_valid "$(t ask_llm_model)" "$W_LLM_MODEL" || return 1
  W_LLM_MODEL="$UI_VALUE"
}

# 汇总页：0 确认、1-8 回头修改对应项、9 取消；确认返回 0，取消返回 1
wizard_summary() {
  local gpu pw llm
  while :; do
    if [ "$W_GPU" = 1 ]; then gpu=$(t value_enabled); else gpu=$(t value_disabled); fi
    if [ "$W_PASSWORD_GENERATED" = 1 ]; then pw="******** ($(t value_generated))"; else pw="********"; fi
    llm="${W_LLM_BASE_URL:-$(t value_not_configured)}"
    UI_DEFAULT=0
    ui_menu "$(t summary_title)" \
      "$(t summary_confirm)" \
      "$(t summary_models "$W_MODELS_DIR")" \
      "$(t summary_identity "$W_PUID:$W_PGID")" \
      "$(t summary_gpu "$gpu")" \
      "$(t summary_port "$W_PORT")" \
      "$(t summary_bind "$W_BIND")" \
      "$(t summary_password "$pw")" \
      "$(t summary_timezone "$W_TZ")" \
      "$(t summary_llm "$llm")" \
      "$(t summary_cancel)" || return 1
    case "$UI_CHOICE" in
      0) return 0 ;;
      1) choose_models_dir ;;
      2) choose_identity ;;
      3) choose_gpu ;;
      4) choose_port ;;
      5) choose_bind ;;
      6) choose_password ;;
      7) choose_timezone ;;
      8) choose_llm ;;
      *) return 1 ;;
    esac
  done
}

install_final_page() {
  local url
  printf '\n' >&2
  ok "$(t install_done)"
  info "$(t final_urls)"
  while IFS= read -r url; do
    [ -n "$url" ] && info "  $url"
  done <<EOF
$(access_urls "$W_BIND" "$W_PORT")
EOF
  if [ "$W_PASSWORD_GENERATED" = 1 ]; then
    warn "$(t final_password_generated "$W_PASSWORD")"
  fi
  info "$(t final_env_location "$LP_HOME/.env")"
  info "$(t final_commands)"
}

wizard_run() {
  wizard_defaults
  W_DOCKER_GID=$(detect_docker_gid)
  W_TZ=$(detect_timezone)
  info "$(t wizard_intro)"
  if ! { choose_models_dir && choose_identity && choose_gpu && choose_port &&
    choose_bind && choose_password && choose_timezone && choose_llm && wizard_summary; }; then
    warn "$(t install_cancelled)"
    return 1
  fi
  if ! apply_install; then
    err "$(t apply_failed)"
    return 1
  fi
  ok "$(t install_written "$LP_HOME")"
  if ui_confirm "$(t ask_start_now)" y; then
    cmd_start
  fi
  install_final_page
}

# cmd_install [默认目录]
cmd_install() {
  local target st
  if ! platform_ok; then
    err "$(t unsupported_platform)"
    return 1
  fi
  if ! { : <"$LP_TTY"; } 2>/dev/null; then
    err "$(t no_tty)"
    return 1
  fi
  info ""
  info "$(t install_welcome "$LLAMAPAD_SCRIPT_VERSION")"
  require_docker || return 1
  while :; do
    ui_input "$(t ask_install_dir)" "${1:-$LLAMAPAD_DEFAULT_HOME}" || return 1
    target=$(abs_path "$UI_VALUE")
    case "$target" in
      *[[:space:]:]*) warn "$(t install_dir_invalid)" ;;
      *) break ;;
    esac
  done
  st=$(dir_state "$target")
  if [ "$st" = installed ]; then
    LP_HOME="$target"
    ok "$(t already_installed "$target")"
    main_menu
    return
  fi
  ensure_dir_writable "$target" || return 1
  LP_HOME="$target"
  place_self "$target" || return 1
  install_launcher "$target"
  if [ "$st" = adopt ]; then
    adopt_run
  else
    wizard_run
  fi
}

# ===== 10. 运维命令 =====

compose() {
  (cd "$LP_HOME" && dk compose "$@")
}

panel_running() {
  [ "$(dk inspect -f '{{.State.Running}}' "$LLAMAPAD_CONTAINER" 2>/dev/null)" = true ]
}

# 启动前检查；DOCKER_GID 每次按 sock 实际属组写回（换机、重装 docker 后 gid 会变）
preflight_start() {
  local envf="$LP_HOME/.env" gid cur port models puid pgid owner
  if [ ! -f "$envf" ]; then
    err "$(t env_missing)"
    return 1
  fi
  gid=$(detect_docker_gid)
  cur=$(env_get "$envf" DOCKER_GID)
  if [ -n "$gid" ] && [ "$gid" != "$cur" ]; then
    env_set "$envf" DOCKER_GID "$gid" && info "$(t gid_synced "$gid")"
  fi
  if ! panel_running; then
    port=$(env_get "$envf" PANEL_PORT)
    port="${port:-$LLAMAPAD_DEFAULT_PORT}"
    if port_in_use "$port"; then
      err "$(t port_busy "$port")"
      return 1
    fi
  fi
  models=$(models_abs "$(env_get "$envf" MODELS_DIR)")
  if [ ! -d "$models" ]; then
    err "$(t models_missing "$models")"
    return 1
  fi
  puid=$(env_get "$envf" PUID)
  pgid=$(env_get "$envf" PGID)
  puid="${puid:-1000}"
  pgid="${pgid:-1000}"
  owner=$(stat_owner "$LP_HOME/data")
  if [ "$owner" != "$puid:$pgid" ]; then
    warn "$(t data_owner_mismatch "$owner" "$puid:$pgid")"
    if ui_confirm "$(t ask_fix_owner)" y; then
      fix_owner "$LP_HOME/data" "$puid" "$pgid" || return 1
    fi
  fi
  case "$(env_get "$envf" COMPOSE_FILE)" in
    *gpu*)
      if ! gpu_runtime_ok; then
        err "$(t gpu_runtime_missing)"
        return 1
      fi
      ;;
  esac
}

http_code() {
  if command -v curl >/dev/null 2>&1; then
    curl -s -o /dev/null -w '%{http_code}' --max-time 2 "$1" 2>/dev/null
  elif command -v wget >/dev/null 2>&1; then
    wget -q --spider -T 2 "$1" 2>/dev/null && printf 200
  fi
}

# 轮询 /login 至 200；上限 LLAMAPAD_READY_TIMEOUT 秒（默认 60）
wait_ready() {
  local envf="$LP_HOME/.env" port bind host i=0 limit="${LLAMAPAD_READY_TIMEOUT:-60}"
  port=$(env_get "$envf" PANEL_PORT)
  bind=$(env_get "$envf" PANEL_BIND)
  case "$bind" in
    "" | 0.0.0.0) host=127.0.0.1 ;;
    *) host="$bind" ;;
  esac
  while [ "$i" -lt "$limit" ]; do
    [ "$(http_code "http://$host:${port:-$LLAMAPAD_DEFAULT_PORT}/login")" = 200 ] && return 0
    sleep 1
    i=$((i + 1))
  done
  return 1
}

print_access() {
  local url
  info "$(t access_title)"
  while IFS= read -r url; do
    [ -n "$url" ] && info "  $url"
  done <<EOF
$(access_urls "$(env_get "$LP_HOME/.env" PANEL_BIND)" "$(env_get "$LP_HOME/.env" PANEL_PORT)")
EOF
}

# _compose_up [额外参数...]：公共的 up + 等待就绪 + 打印地址
_compose_up() {
  if ! compose up -d "$@"; then
    err "$(t start_failed)"
    return 1
  fi
  if ! wait_ready; then
    err "$(t panel_not_ready "${LLAMAPAD_READY_TIMEOUT:-60}")"
    return 1
  fi
  ok "$(t panel_ready)"
  print_access
}

cmd_start() {
  preflight_start || return 1
  info "$(t starting)"
  _compose_up
}

# 强制重建：compose 只在编排变化时才重建，改 .env 里被插值的值也要确保生效
cmd_restart() {
  preflight_start || return 1
  info "$(t restarting)"
  _compose_up --force-recreate
}

running_models() {
  dk ps --filter label=llamapad.managed=true --format '{{.Names}}' 2>/dev/null
}

cmd_stop() {
  local models
  models=$(running_models)
  if ! compose stop; then
    err "$(t stop_failed)"
    return 1
  fi
  ok "$(t stopped)"
  if [ -n "$models" ]; then
    warn "$(t models_still_running "$(printf '%s' "$models" | tr '\n' ' ')")"
    if ui_confirm "$(t ask_stop_models)" n; then
      # shellcheck disable=SC2086
      dk stop $models
    fi
  fi
}

panel_status_text() {
  local s
  s=$(dk ps -a --filter "name=^${LLAMAPAD_CONTAINER}$" --format '{{.Status}}' 2>/dev/null | head -n 1)
  printf '%s' "${s:-$(t status_not_created)}"
}

cmd_status() {
  local envf="$LP_HOME/.env" model gpus models_dir
  model=$(dk ps --filter label=llamapad.managed=true --format '{{.Label "llamapad.model"}}' 2>/dev/null | head -n 1)
  info "$(t status_panel "$(panel_status_text)")"
  info "$(t status_image "$LLAMAPAD_IMAGE" "$(env_get "$envf" LLAMAPAD_VERSION)")"
  info "$(t status_listen "$(env_get "$envf" PANEL_BIND)" "$(env_get "$envf" PANEL_PORT)")"
  info "$(t status_model "${model:-$(t status_model_none)}")"
  if command -v "$LP_NVIDIA_SMI" >/dev/null 2>&1; then
    gpus=$("$LP_NVIDIA_SMI" --query-gpu=name,memory.used,memory.total --format=csv,noheader 2>/dev/null | paste -sd ';' -)
    [ -n "$gpus" ] && info "$(t status_gpu "$gpus")"
  fi
  models_dir=$(models_abs "$(env_get "$envf" MODELS_DIR)")
  info "$(t status_disk "$LP_HOME/data" "$(fmt_kb "$(df_avail_kb "$LP_HOME/data")")")"
  [ -d "$models_dir" ] && info "$(t status_disk "$models_dir" "$(fmt_kb "$(df_avail_kb "$models_dir")")")"
  return 0
}

cmd_logs() {
  if [ "$OPT_FOLLOW" = 1 ]; then
    compose logs --tail 200 -f
  else
    compose logs --tail 200
  fi
}

menu_header() {
  local envf="$LP_HOME/.env" model url
  model=$(dk ps --filter label=llamapad.managed=true --format '{{.Label "llamapad.model"}}' 2>/dev/null | head -n 1)
  printf '\n' >&2
  info "  $(t menu_title)   $(t menu_versions "$LLAMAPAD_SCRIPT_VERSION" "$(env_get "$envf" LLAMAPAD_VERSION)")"
  info "  $(t menu_dir "$LP_HOME")   $(t status_panel "$(panel_status_text)")   $(t status_model "${model:-$(t status_model_none)}")"
  url=$(access_urls "$(env_get "$envf" PANEL_BIND)" "$(env_get "$envf" PANEL_PORT)" | head -n 1)
  [ -n "$url" ] && info "  $url"
  printf '\n' >&2
}

# 把 .env 读回 W_*，供修改配置复用安装向导的 choose_* 函数
config_load_env() {
  local envf="$LP_HOME/.env" v
  wizard_defaults
  v=$(env_get "$envf" LLAMAPAD_VERSION) && [ -n "$v" ] && W_VERSION="$v"
  v=$(env_get "$envf" MODELS_DIR) && [ -n "$v" ] && W_MODELS_DIR="$v"
  v=$(env_get "$envf" PUID) && [ -n "$v" ] && W_PUID="$v"
  v=$(env_get "$envf" PGID) && [ -n "$v" ] && W_PGID="$v"
  v=$(env_get "$envf" PANEL_PORT) && [ -n "$v" ] && W_PORT="$v"
  v=$(env_get "$envf" PANEL_BIND) && [ -n "$v" ] && W_BIND="$v"
  v=$(env_get "$envf" PANEL_ADMIN_PASSWORD) && W_PASSWORD="$v"
  v=$(env_get "$envf" TZ) && [ -n "$v" ] && W_TZ="$v"
  v=$(env_get "$envf" DOCKER_GID) && W_DOCKER_GID="$v"
  W_LLM_BASE_URL=$(env_get "$envf" PANEL_LLM_BASE_URL)
  W_LLM_API_KEY=$(env_get "$envf" PANEL_LLM_API_KEY)
  W_LLM_MODEL=$(env_get "$envf" PANEL_LLM_MODEL)
  case "$(env_get "$envf" COMPOSE_FILE)" in *gpu*) W_GPU=1 ;; esac
  if [ -d "$(models_abs "$W_MODELS_DIR")" ]; then W_MODELS_NEW=0; else W_MODELS_NEW=1; fi
}

cmd_config() {
  local envf="$LP_HOME/.env" changed=0 gpu llm allow
  while :; do
    config_load_env
    if [ "$W_GPU" = 1 ]; then gpu=$(t value_enabled); else gpu=$(t value_disabled); fi
    llm="${W_LLM_BASE_URL:-$(t value_not_configured)}"
    ui_menu "$(t config_title)" \
      "$(t summary_port "$W_PORT")" \
      "$(t summary_bind "$W_BIND")" \
      "$(t summary_models "$W_MODELS_DIR")" \
      "$(t summary_identity "$W_PUID:$W_PGID")" \
      "$(t summary_gpu "$gpu")" \
      "$(t summary_timezone "$W_TZ")" \
      "$(t summary_llm "$llm")" \
      "$(t config_password)" \
      "$(t config_back)" || break
    case "$UI_CHOICE" in
      0)
        # 面板正在运行时它自己占着当前端口，不能因此判为「被占用」
        allow=""
        if [ "$DK_STATE" = ok ] && panel_running; then allow="$W_PORT"; fi
        choose_port "$allow" && env_set "$envf" PANEL_PORT "$W_PORT" && changed=1
        ;;
      1) choose_bind && env_set "$envf" PANEL_BIND "$W_BIND" && changed=1 ;;
      2)
        if choose_models_dir && ensure_models_dir && env_set "$envf" MODELS_DIR "$W_MODELS_DIR"; then
          warn "$(t config_models_note)"
          changed=1
        fi
        ;;
      3)
        # 先落实属主再写 .env：属主改不了时旧身份仍与 data/ 一致，不留下「配置已改、目录属主未改」的中间态
        if choose_identity; then
          if fix_owner "$LP_HOME/data" "$W_PUID" "$W_PGID"; then
            env_set "$envf" PUID "$W_PUID" && env_set "$envf" PGID "$W_PGID" && changed=1
          else
            err "$(t identity_apply_failed)"
          fi
        fi
        ;;
      4) choose_gpu && env_set "$envf" COMPOSE_FILE "$(compose_file_value "$W_GPU")" && changed=1 ;;
      5) choose_timezone && env_set "$envf" TZ "$W_TZ" && changed=1 ;;
      6)
        choose_llm force && env_set "$envf" PANEL_LLM_BASE_URL "$W_LLM_BASE_URL" &&
          env_set "$envf" PANEL_LLM_API_KEY "$W_LLM_API_KEY" &&
          env_set "$envf" PANEL_LLM_MODEL "$W_LLM_MODEL" && changed=1
        ;;
      7)
        if choose_password && env_set "$envf" PANEL_ADMIN_PASSWORD "$W_PASSWORD"; then
          [ "$W_PASSWORD_GENERATED" = 1 ] && warn "$(t config_password_generated "$W_PASSWORD")"
          info "$(t config_password_note)"
          changed=1
        fi
        ;;
      *) break ;;
    esac
  done
  [ "$changed" = 1 ] || return 0
  if ui_confirm "$(t ask_apply_now)" y; then
    cmd_restart
  else
    info "$(t config_apply_later)"
  fi
}

main_menu() {
  local start_label
  require_docker || return 1
  while :; do
    menu_header
    if panel_running; then start_label=$(t item_restart); else start_label=$(t item_start); fi
    ui_menu "" "$start_label" "$(t item_stop)" "$(t item_status)" "$(t item_logs)" "$(t item_config)" \
      "$(t item_upgrade)" "$(t item_doctor)" "$(t item_uninstall)" "$(t item_exit)" || return 0
    case "$UI_CHOICE" in
      0) if panel_running; then cmd_restart; else cmd_start; fi ;;
      1) cmd_stop ;;
      2) cmd_status ;;
      3) OPT_FOLLOW=0; cmd_logs ;;
      4) cmd_config ;;
      5) cmd_upgrade ;;
      6) cmd_doctor ;;
      7) cmd_uninstall && [ ! -d "$LP_HOME" ] && return 0 ;;
      *) return 0 ;;
    esac
    ui_pause
  done
}

# ===== 11. 接管 =====

# ===== 12. 升级 =====

# ===== 13. 自检与卸载 =====

# ===== 14. 入口 =====

cmd_help() {
  local c
  t usage
  printf '\n\n%s\n' "$(t help_commands_title)"
  for c in install start stop restart status logs config upgrade doctor uninstall help version; do
    printf '  %-10s %s\n' "$c" "$(t "help_$c")"
  done
  printf '\n%s\n' "$(t help_options_title)"
  printf '  %-16s %s\n' \
    "--dir DIR" "$(t help_opt_dir)" \
    "--lang zh|en" "$(t help_opt_lang)" \
    "--to VERSION" "$(t help_opt_to)" \
    "-f, --follow" "$(t help_opt_follow)"
}

parse_args() {
  while [ $# -gt 0 ]; do
    case "$1" in
      --dir) OPT_DIR="${2:-}"; shift ;;
      --dir=*) OPT_DIR="${1#--dir=}" ;;
      --lang) OPT_LANG="${2:-}"; shift ;;
      --lang=*) OPT_LANG="${1#--lang=}" ;;
      --to) OPT_TO="${2:-}"; shift ;;
      --to=*) OPT_TO="${1#--to=}" ;;
      -f | --follow) OPT_FOLLOW=1 ;;
      -h | --help) CMD=help ;;
      -*) detect_lang; err "$(t unknown_option "$1")"; return 2 ;;
      *)
        if [ -z "$CMD" ]; then CMD="$1"; else detect_lang; err "$(t extra_argument "$1")"; return 2; fi
        ;;
    esac
    shift
  done
}

main() {
  local home
  parse_args "$@" || exit 2
  detect_lang
  case "$CMD" in
    help) cmd_help; return 0 ;;
    version) printf '%s\n' "$LLAMAPAD_SCRIPT_VERSION"; return 0 ;;
  esac
  trap ui_restore EXIT
  trap 'ui_restore; exit 130' INT TERM

  home=$(home_candidate)
  if [ -n "$home" ] && [ "$(dir_state "$home")" = installed ]; then
    LP_HOME="$home"
    case "$CMD" in
      "" | install) main_menu ;;
      doctor) cmd_doctor ;;
      start | stop | restart | status | logs | config | upgrade | uninstall) require_docker && "cmd_$CMD" ;;
      *) err "$(t unknown_command "$CMD")"; return 2 ;;
    esac
    return
  fi

  case "$CMD" in
    # 默认目录只取显式给出的（--dir / LLAMAPAD_HOME），不取脚本所在目录——在仓库里跑时那是 deploy/
    "" | install) cmd_install "${OPT_DIR:-${LLAMAPAD_HOME:-}}" ;;
    start | stop | restart | status | logs | config | upgrade | doctor | uninstall)
      err "$(t not_installed)"
      return 1
      ;;
    *) err "$(t unknown_command "$CMD")"; return 2 ;;
  esac
}

if [ "${LLAMAPAD_SOURCE_ONLY:-}" != "1" ]; then
  main "$@"
fi
